# Receives an event and uses the Classifier AI to understand it and routes to the right agent+task
# Parses the AI's JSON response, and routes the execution to the correct specialized agent

import json
from crewai import Crew
from settings import salesperson, classifier, support, post_sales
from task_builder import task_sales, task_followup, task_classifier, task_support, task_post_sales

def run_crew(agent, task):
    """
    Run a single agent and task.
    Returns the string output generated by the LLM.
    """
    return Crew(agents=[agent], tasks=[task]).kickoff()


def orchestrate(event_type, event_data):
    """
    Handles different types of system events.
    """
    if event_type == "new_message":

        # Classifier reads the message and output a JSON decision
        task_class = task_classifier(event_data)
        class_response = run_crew(classifier, task_class)

        try:
            # Convert the AI's string response into a Python Dictionary
            decision = json.loads(str(class_response))

        except json.JSONDecodeError:
            # Security Fallback in case AI miss the JSON format
            return "Erro: O agente classificador se confundiu. Tente novamente."


        # Execute based on AI decision ("next_agent" key from the JSON)
        if decision["next_agent"] == "classifier":
            # Classifier did not identify the client needs. The classifier generated a greeting. Return it directly to UI
            return decision["msg_to_client"]
            
        elif decision["next_agent"] == "sales":
            # Classifier identify a sale. Call the sales task and the sales agent
            task = task_sales(event_data)
            return run_crew(salesperson, task)
            
        elif decision["next_agent"] == "support":
            # Classifier identify a doubt/complaint. Call the support agent
            task = task_support(event_data)
            return run_crew(support, task)

        elif decision["next_agent"] == "human":
            # The client is angry or wants a human. Return the trigger tag.
            # The interface.py will intercept this specific string and activate the handoff.
            return "[HANDOFF] Transferindo para um atendente humano."


    # Follow_up task is triggered by a CRM when a lead goes cold (simulated button)
    elif event_type == "inactive_lead":
        task = task_followup(event_data)
        return run_crew(salesperson, task)

    # post_sales task is triggered by a CRM after a service is done (simulated button)
    elif event_type == "post_sales":
        task = task_post_sales(event_data)
        return run_crew(post_sales, task)

    # Fallback if an unknown event is sent to the orchestrator
    return "Erro: Tipo de evento desconhecido."